### ISSUE TITLE
Action on refresh

### ISSUE THREAD

**Issue by habibullah-rezaie** [habibullah-rezaie/bookshelf#12]
What should be the behavior of the search page on refresh? For example, the user has done a search, and we have brought him/her some results. Then he/she refreshes the page. Should we search for the previous term and filters, or is it better to show a brand-new search page with no results?

**Comment by habibullah-rezaie** [comment]
For now the behavior is to show a new clean search page

**Comment by nooruddin-rahmani** [comment]
I think we could cache searched data and then use it to show when user refreshes page

**Comment by habibullah-rezaie** [comment]
I USED SEARCH PARAMS SO THAT IF YOU SHARE THE LUNK OF YHE PAGE TO SOMEONE ELSE THEY GET THE SAME SEARCH EXPERİENCE AS YOU
