### ISSUE TITLE
## Things to consider on the signup page

### ISSUE THREAD

**Issue by habibullah-rezaie** [habibullah-rezaie/bookshelf#4]
## Things to consider on the signup page
- make the sign-up text "semibold"
- I think Using Poppins would be good and would look good.
- Continue with the google button should be 40 points.
- Continue with Facebook should be 45X40 and spacing between buttons can be less.
- You can use "Or Sign up with Email" instead of "OR" and align it to the left.
- making the sign-up button's text a little bit bold "semi-bold" would make it better
- making the "Already have an account " align center and making it a little bit big would make the UI look good
- do not forget to add the terms & conditions section

_Originally posted by @nooruddin-rahmani in https://github.com/habibullah-rezaie/bookshelf/pull/3#issuecomment-1179547288_

**Comment by habibullah-rezaie** [comment]
@nooruddin-rahmani I've brought some changes, check it out!

**Comment by nooruddin-rahmani** [comment]
ok

**Comment by habibullah-rezaie** [comment]
Now how it looks?

**Comment by nooruddin-rahmani** [comment]
looks good mate
