### ISSUE TITLE
Styles of filter modal

### ISSUE THREAD

**Issue by habibullah-rezaie** [habibullah-rezaie/bookshelf#8]
What skin color should I use instead of purple in here?

**Comment by habibullah-rezaie** [comment]
![Screenshot_20221102-212416_Chrome.jpg](https://user-images.githubusercontent.com/71997884/199571894-35002b9d-0f63-4807-9319-fabb98413540.jpg)

**Comment by nooruddin-rahmani** [comment]
We could use the primary color for buttons

**Comment by nooruddin-rahmani** [comment]
not black but Blackish:)
#565454

**Comment by habibullah-rezaie** [comment]
@nooruddin-rahmani Please have a recheck
